### ISSUE TITLE
Distribute Goxygen as a Docker image

### ISSUE THREAD

**Issue by Shpota** [Shpota/goxygen#100]
Add an ability to run Goxygen from a Docker image so that a user would not have to `go get` the Goxygen package.
Add a CI step to build and push docker images to [GitHub Packages](https://github.com/features/packages).

**Comment by orgmatileg** [comment]
Let me help!

**Comment by Shpota** [comment]
Thanks @orgmatileg!

**Comment by orgmatileg** [comment]
Hi, I just make a draft for PR later, there is still permission issues

orgmatileg:feature/ci-docker-build-and-push

#107

**Comment by orgmatileg** [comment]
Hi, Please review the latest PR, all done..

You can try using this code from my fork
`docker run -e UID=$(echo $UID) -e GID=$(echo $GID) -v $(pwd):/app/generated ghcr.io/orgmatileg/goxygen:ci-docker-build-and-push init my-app`
