### ISSUE TITLE
can only use path@version syntax with 'go get'

### ISSUE THREAD

**Issue by VedantMadane** [Shpota/goxygen#106]
I am on go version 1.15.15. On running 
`
go run github.com/shpota/goxygen@latest init --frontend vue --db mongo my-app
`

I am getting this error:
`
can only use path@version syntax with 'go get'
`

**Comment by Shpota** [comment]
The `@latest` works starting from Go 1.17. Please follow the instructions for [the older versions of Go](https://github.com/Shpota/goxygen#how-to-use):

> Go 1.11 - 1.15
> 
> Run
> 
> ```
> go get -u github.com/shpota/goxygen
> go run github.com/shpota/goxygen init my-app
> ```

In your case, this should work:
```
go get -u github.com/shpota/goxygen
go run github.com/shpota/goxygen@latest init --frontend vue --db mongo my-app
```
