### ISSUE TITLE
Add Angular support

### ISSUE THREAD

**Issue by Shpota** [Shpota/goxygen#16]

**Comment by carasue** [comment]
Are u planning to support Vue?

**Comment by Shpota** [comment]
Yes, and most likely I will do that before Angular as I've received several requests to add Vue.

**Comment by Jakob-em** [comment]
What is the status on this. I would like to help with the angular support.

**Comment by Shpota** [comment]
Thank you @Jakob-em. We can certainly elaborate on this. I am planning to start working on Vue and Angular support this week. Please join the Gitter channel (link in the header of readme) so we can discus the next steps there.
