### ISSUE TITLE
Idea for collaboration with Create Go App

### ISSUE THREAD

**Issue by koddr** [Shpota/goxygen#17]
Hi, @Shpota  👋 

I started similar project (on Dec 2019) called `Create Go App` ([link](https://github.com/create-go-app)). I already wrote some templates, configure Docker images and stable CLI for `cgapp` (for a short). But, unfortunately, I don't have time to bring it all to mind, because I'm hard working for dev, improve and promo my own Go web framework — [Fiber](https://github.com/gofiber/fiber) — at this moment.

I just dream about a tool, like you and I did! And I wanted to work with you together for it. For example, we can re-base your project to my organization and I give you all member (admin) rights.

> Agree, this CLI is more like `Create Go App`, than `goxygen`, because does similar function like `create-react-app` 😉 

Please, think about it.

— Vic Shóstak

**Comment by Shpota** [comment]
Hi Vic,

Thank you for the suggestion. It is interesting that we came up with similar project ideas 🙂 
I will certainly think about your suggestion.

Best,
Sasha.
