### ISSUE TITLE
Add support for different database systems

### ISSUE THREAD

**Issue by Jakob-em** [Shpota/goxygen#33]
It would be cool if goxygen would support other databases than MongoDB. A good start would be to support SQL databases like MySql. 
The user should then be able to choose during the generation which database he wants to use.

**Comment by rjtch** [comment]
It would also be better to add more support for javascript frameworks like angular.

**Comment by Shpota** [comment]
@rjtch this is already in progress. Most of the functionality is already in place (see the corresponding [Vue](https://github.com/Shpota/goxygen/pull/26) and [Angular](https://github.com/Shpota/goxygen/pull/25) PRs ). Right now we are working on unifying the implementations and adding CLI arguments to be able to select a framework.

**Comment by SrGeneroso** [comment]
In my case I've choosen this boilerplate because of Mongo and Vue, although the more the merrier.
