### ISSUE TITLE
Vue template fails to build with "docker-compose up"

### ISSUE THREAD

**Issue by Shpota** [Shpota/goxygen#37]
How to reproduce.

Navigate to `cli/cli.go` and change the 20th line from `codegen.Generate(projectName, "react")` to `codegen.Generate(projectName, "vue")`.

From command line perform.
```
cd transform
go run transformer.go
cd ..
go run main.go init my-app
cd my-app
docker-compose up
```
**AR:** Execution fails with `npm ERR! missing script: build:prod`.

**How to fix:** Introduce an alias in the corresponding `package.json`.

**Comment by Jakob-em** [comment]
Could be easily fixed for now by adding the build:prod goal to the package.json of the Vue project
