### ISSUE TITLE
Translate missing sentences in Chinese README (help wanted) 

### ISSUE THREAD

**Issue by Shpota** [Shpota/goxygen#41]
The Chinese version of README has too be updated.

Please translate the English sentences in https://github.com/Shpota/goxygen/blob/cli/.github/README_zh.md

**Comment by lzane** [comment]
hello, 
only got one sentence to translate, is it right? #42

**Comment by Shpota** [comment]
@lzane , thank you for the translation!

There are also two small places:
This:
> ## 生成的项目的结构 (React-based app)
And in the next sentence 
> 并将其与前端的React组件相连

the word "React" has to be dropped. From "connects it with front end React components"  to  "connects them with front end components".

**Comment by lzane** [comment]
@Shpota done.

I also review the whole file based on the english version and find the following issues.

- delete weird line wrap.
- change the order of "Dependencies" and "Structure of a generated project (React-based app)"

fix them as well in the same pr.

**Comment by Shpota** [comment]
Thank you @lzane !
