### ISSUE TITLE
Add more translations for README

### ISSUE THREAD

**Issue by Shpota** [Shpota/goxygen#43]
If you speak any other language from the listed in the README and have the willingness to translate it to your language please do that.

The most recent version of the English version of  README can be found [here](https://github.com/Shpota/goxygen/blob/master/.github/README.md).

**Comment by lzane** [comment]
@Shpota The link is 404 🤣

**Comment by Shpota** [comment]
@lzane thank you. Corrected the link.

**Comment by SrGeneroso** [comment]
I've sent you a pull request fot the spanish translation.

**Comment by ofirrock** [comment]
Sent a pull request for Hebrew translation (#78).
