### ISSUE TITLE
Postgres support?

### ISSUE THREAD

**Issue by sokoow** [Shpota/goxygen#63]
Do you plan postgres support ? If you need help, can you document what shoud be done ?

**Comment by Shpota** [comment]
Hi @sokoow !

Thank you for offering help.

The PostgreSQL part is in progress. Here is the corresponding [pull request](https://github.com/Shpota/goxygen/pull/55). The major part of the implementation is done, but I didn't have enough time to complete it.

There is [a Gitter chat](https://gitter.im/goxygen/community) where we can discuss what else can be done.
