### ISSUE TITLE
Frontend and backend hot reload ?

### ISSUE THREAD

**Issue by ljesparis** [Shpota/goxygen#68]
Does any frontend template support hot reload?

Backend hot reload could be added as well. Maybe [air](https://github.com/cosmtrek/air) support could be added?

**Comment by Shpota** [comment]
Yes, you can use hot reload with all three supported front end frameworks.

In development mode, the front end files will be automatically reloaded. You only need to start the front end like this:
```
npm install
npm start
```
The generated project contains a README file with instructions on how to run the application in development and production modes. You can find more details there.
