### ISSUE TITLE
Integration tests that start a generated application in a container and ensure it accepts requests

### ISSUE THREAD

**Issue by Shpota** [Shpota/goxygen#71]
At the moment, the project has [integration tests](https://github.com/Shpota/goxygen/blob/master/.github/workflows/verify-templates.yml) that generate applications with different front end frameworks and ensure that they are "buildable" using the `docker build` command.

This however doesn't grantee that the generated application will run. For instance, if a database connection string is wrong or in case of any other issue. 

It would be better if the integration tests would not only build the container but also start the application and query it via an HTTP call to ensure it started and serves requests.

One the high level it could be done in in three steps:
1. Start the application using `docker-compose up`
2. Wait until the application starts. Could be achieved using a container running [wait-for-it.sh](https://github.com/vishnubob/wait-for-it).
3. Query the application using `curl` or in any other way. It could include an http call to the applications REST API as well as querying the front end.
4. Shut down the application.

**Comment by Jakob-em** [comment]
I will give this issue a try

**Comment by Jakob-em** [comment]
Maybe we could also simplify the current pipeline to not duplicate the steps and instead parametrize the jobs. This would also prepare us for the extension with new tests for the upcoming release (support for different databases). So for example you just have to type all frontend options and all database options and then every possible combination of those options is build and tested. I think github actions has a way for doing this.

**Comment by Jakob-em** [comment]
Should we keep the `build` workflow or is the new workflow (which includes the build) enough?
